.TH SSH-LDAP-PUBLICKEY 8 "13 August 2014"

.SH NAME
\fBssh-ldap-publickey\fP \- program for looking up SSH public keys with LDAP

.SH SYNOPSIS
\fBssh-ldap-publickey\fP \fIUSERNAME\fP

.SH DESCRIPTION
\fBssh-ldap-publickey\fP searches the LDAP directory configured in
ldap.conf(5) for a POSIX account with the given \fIUSERNAME\fP that has the
ldapPublicKey object class. If an entry is found, all of its sshPublicKey
attributes are written to stdout, separated by new lines.

\fBssh-ldap-publickey\fP can be used as OpenSSH's AuthorizedKeysCommand by
adding the following lines to sshd_config(5):

.DS
  AuthorizedKeysCommand /usr/bin/ssh-ldap-publickey
  AuthorizedKeysCommandUser nobody
.DE

This allows authorized SSH public keys to be fetched from LDAP, rather than the
user's authorized_keys(5) file.

.SH SEE ALSO
ldap.conf(5),
sshd_config(5)

.SH URL
http://grahamedgecombe.com/projects/ssh-ldap-publickey

.SH AUTHOR
Graham Edgecombe <graham@grahamedgecombe.com>
